import numpy as np
from nqs_frustrated_phase import *
hphi.write_settings(square.Square24, j2=0.55, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/square/24/0.55')
# hphi.write_settings(square.Square36, j2=0.40, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/square/36/0.4')
# hphi.write_settings(square.Square36, j2=0.55, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/square/36/0.55')
# hphi.write_settings(square.Square36, j2=1.0, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/square/36/1.0')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=0.70, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/0.7')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=0.80, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/0.8')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=0.90, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/0.9')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.0, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.0')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.1, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.1')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.2, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.2')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.3, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.3')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.4, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.4')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.5, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.5')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.6, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.6')
# hphi.write_settings(triangle.TrianglePeriodic30, j2=1.7, workdir='/zfs/hybrilit.jinr.ru/user/a/astrakh/nqs_frustrated_phase/data/triangle/30/1.7')
